---
wordpress_image: docker.io/library/wordpress:7.1.2-php8.4-apache
wordpress_mysql_image: docker.io/library/mysql:8.4.11
wordpress_exporter_image: docker.io/prom/mysqld-exporter:v0.20.0

wordpress_url: "https://{{ angie_vhosts.wordpress.server_name }}"

wordpress_db_name: wordpress
wordpress_db_user: wordpress
wordpress_exporter_user: exporter

wordpress_mysql_root_password: "{{ vault_mysql_root_password }}"
wordpress_db_password: "{{ vault_wordpress_db_password }}"
wordpress_exporter_password: "{{ vault_mysqld_exporter_password }}"
wordpress_salts: "{{ vault_wordpress_salts }}"

wordpress_memory_limit: 256Mi
wordpress_mysql_memory_limit: 512Mi
