- name: Install and configure Docker
  block:
    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - python3-pip
          - python3-setuptools
          - python3-docker
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes

    - name: Install Docker CE
      ansible.builtin.apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Ensure Docker service is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
  become: true
  tags:
    - docker
    - install

- name: Configure Docker network and application
  block:
    - name: Create Docker network
      community.docker.docker_network:
        name: balancer_network
        driver: bridge
        state: present
      register: docker_network

    - name: Prepare application directory
      ansible.builtin.file:
        path: /opt/angie
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Copy Docker Compose file
      ansible.builtin.template:
        src: docker_compose_debug.yml
        dest: /opt/angie/docker-compose.yml
        mode: '0644'
        owner: root
        group: root
        validate: docker compose -f %s config
      register: compose_file

    - name: Deploy Docker Compose stack
      community.docker.docker_compose:
        project_src: /opt/angie
        files:
          - docker-compose.yml
        state: present
        pull: yes 
      register: docker_stack
      notify: cleanup docker
  become: true
  tags:
    - docker
    - deploy
