locals {
  # Группа на каждое значение ansible_groups плюс группа окружения из label environment.
  host_groups = {
    for name, vm in var.vms : name => distinct(concat(
      vm.ansible_groups,
      compact([lookup(vm.labels, "environment", "")]),
    ))
  }

  groups = distinct(flatten(values(local.host_groups)))

  inventory = {
    all = {
      vars = {
        ansible_user = var.ssh_user
      }
      hosts = {
        for name, vm in var.vms : name => {
          ansible_host = coalesce(vm.public_ip, vm.private_ip)
        }
      }
      children = {
        for group in local.groups : group => {
          hosts = {
            for name, groups in local.host_groups : name => null if contains(groups, group)
          }
        }
      }
    }
  }
}

resource "local_file" "inventory" {
  filename        = var.inventory_file
  file_permission = "0644"
  content         = "# Generated by Terraform (modules/ansible_inventory), do not edit.\n${yamlencode(local.inventory)}"
}

output "inventory_yaml" {
  value = local_file.inventory.content
}

output "inventory_file" {
  value = local_file.inventory.filename
}
