- name: Get local ACME directories status
  ansible.builtin.stat:
    path: "{{ local_backup_dir }}/{{ item }}"
  register: local_dirs
  delegate_to: localhost
  become: false
  loop: "{{ acme_dirs }}"

- name: Get remote ACME directories status
  ansible.builtin.stat:
    path: "/var/lib/angie/acme/{{ item }}"
  register: remote_dirs
  loop: "{{ acme_dirs }}"

- name: Copy ACME directories to remote host
  ansible.builtin.synchronize:
    src: "{{ local_backup_dir }}/{{ item.0 }}/"
    dest: "/var/lib/angie/acme/{{ item.0 }}/"
    mode: push
    rsync_opts:
      - "--chmod=D0700,F0600"
      - "--rsync-path='sudo rsync'"
  when: 
    - item.1.stat.exists  
    - not item.2.stat.exists  
  loop: "{{ acme_dirs | zip(local_dirs.results, remote_dirs.results) | list }}"
  delegate_to: localhost

- name: Copying angie.conf
  ansible.builtin.template:
    src: angie.conf.j2
    dest: "{{ angie_conf_dest }}"
    mode: '0644'
    owner: root
    group: root

- name: Copying site config
  ansible.builtin.template:
    src: redtomat.conf.j2
    dest: "{{ angie_worpress_site }}"
    mode: '0644'

- name: Restart angie
  ansible.builtin.systemd:
    name: angie
    state: restarted
    enabled: true


- name: Check and backup ACME directories
  block:
    - name: Get remote directories status
      ansible.builtin.find:
        paths: /var/lib/angie/acme
        file_type: directory
        patterns: "{{ acme_dirs }}"
      register: remote_dirs_backup

    - name: Create local backup directory if it doesn't exist
      ansible.builtin.file:
        path: "{{ local_backup_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      become: false

    - name: Backup ACME directories to local host
      ansible.builtin.synchronize:
        src: "{{ item.path }}/"
        dest: "{{ local_backup_dir }}/{{ item.path | basename }}/"
        mode: pull
        recursive: yes
        use_ssh_args: yes
        rsync_opts:
          - "--chmod=D0755,F0644"
          - "--rsync-path='sudo rsync'"
      loop: "{{ remote_dirs_backup.files }}"
      when: remote_dirs_backup.matched > 0
      delegate_to: localhost
      become: false

  tags:
    - backup

