- name: Install Angie Pro
  hosts: all
  roles:
    - role: web_server
      vars:
        installation_type: web_server
  tags:
    - angie

- name: Install Angie in docker
  hosts: all
  roles:
    - role: web_server
      vars:
        installation_type: web_server_docker
  tags:
    - angie-docker
