{
 "title": "Angie",
 "description": "Grafana dashboard for Angie (fork of nginx) web server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(angie_connections_active,job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(angie_connections_active{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Active and Idle Connections (stacked)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "angie_connections_active{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Active Connections"
    },
    {
     "expr": "angie_connections_idle{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "Idle Connections"
    }
   ]
  },
  {
   "title": "New Connections",
   "type": "timeseries",
   "description": "Accepted/Dropped Connections",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(angie_connections_accepted{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Accepted Connections"
    },
    {
     "expr": "irate(angie_connections_dropped{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Dropped Connections"
    }
   ]
  },
  {
   "title": "HTTP Server Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zone Received Requests",
     "type": "timeseries",
     "description": "Number of client requests received in an HTTP server zone (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_server_zones_requests_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Requests In Progress",
     "type": "timeseries",
     "description": "Number of client requests currently being processed in an HTTP server zone",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "angie_http_server_zones_requests_processing{instance=\"$node\", job=\"$job\"}",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Zones Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_http_server_zones_data_received{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Received"
      },
      {
       "expr": "irate(angie_http_server_zones_data_sent{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Sent"
      }
     ]
    },
    {
     "title": "Zone Discarded Requests",
     "type": "timeseries",
     "description": "Number of client requests completed in an HTTP server zone without sending a response (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_server_zones_requests_discarded{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "SSL Connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_http_server_zones_ssl_handshaked{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Successful Handshakes"
      },
      {
       "expr": "irate(angie_http_server_zones_ssl_reuses{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Successful Reuses"
      },
      {
       "expr": "irate(angie_http_server_zones_ssl_timedout{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Timeouts"
      },
      {
       "expr": "irate(angie_http_server_zones_ssl_failed{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Failures"
      }
     ]
    },
    {
     "title": "Server Zone Responses - 2xx/3xx Codes",
     "type": "timeseries",
     "description": "Count of responses with 100-399 Status Codes (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_server_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^(1|2|3).*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Zone Responses - 4xx Codes",
     "type": "timeseries",
     "description": "Count of responses with 400-499 Status Codes (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_server_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Zone Responses - 5xx Codes",
     "type": "timeseries",
     "description": "Count of responses with 500-599 Status Codes (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_server_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 4xx errors codes divided by all zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_server_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval])) / increase(angie_http_upstreams_peers_selected_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "5xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 5xx errors codes divided by all zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_server_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval])) / increase(angie_http_server_zones_requests_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Stream Server Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zone Received Connections",
     "type": "timeseries",
     "description": "Number of client connections received in a stream server zone (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_stream_server_zones_connections_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Zones Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_stream_server_zones_data_received{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Received"
      },
      {
       "expr": "irate(angie_stream_server_zones_data_sent{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Sent"
      }
     ]
    },
    {
     "title": "Zone Discarded Connections",
     "type": "timeseries",
     "description": "Number of client connections completed in a stream server zone without establishing a session (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_stream_server_zones_connections_discarded{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Connections In Progress",
     "type": "timeseries",
     "description": "Number of client connections currently being processed in a stream server zone",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "angie_stream_server_zones_connections_processing{instance=\"$node\", job=\"$job\"}",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "SSL Connections",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_stream_server_zones_ssl_handshaked{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Successful Handshakes"
      },
      {
       "expr": "irate(angie_stream_server_zones_ssl_reuses{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Successful Reuses"
      },
      {
       "expr": "irate(angie_stream_server_zones_ssl_timedout{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Timeouts"
      },
      {
       "expr": "irate(angie_stream_server_zones_ssl_failed{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - SSL Failures"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Location Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location Zone Received Requests",
     "type": "timeseries",
     "description": "Number of client requests received in an HTTP server zone (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_location_zones_requests_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Location Zone Discarded Requests",
     "type": "timeseries",
     "description": "Number of client requests completed in an HTTP server zone without sending a response (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_location_zones_requests_discarded{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Location Zone Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_http_location_zones_data_received{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Received"
      },
      {
       "expr": "irate(angie_http_location_zones_data_sent{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - Data Sent"
      }
     ]
    },
    {
     "title": "Location Zone Responses - 2xx/3xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_location_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^(1|2|3).*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Location Zone Responses - 4xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_location_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Location Zone Responses - 5xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (zone) (irate(angie_http_location_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Location 4xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 4xx errors codes divided by all location zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_location_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval])) / increase(angie_http_location_zones_requests_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "Location 5xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 4xx errors codes divided by all location zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_location_zones_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval])) / increase(angie_http_location_zones_requests_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Upstreams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upstream Statuses",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "angie_http_upstreams_peers_state{job=\"$job\", instance=\"$node\"}",
       "legendFormat": "{{ upstream }}/{{ peer }}"
      }
     ]
    },
    {
     "title": "Upstream Health Failures",
     "type": "timeseries",
     "description": "Number of unsuccessful attempts to communicate with an upstream peer in \"HTTP\".",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(angie_http_upstreams_peers_health_fails{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Health Unavailable Events",
     "type": "timeseries",
     "description": "Number of times when an upstream peer in \"HTTP\" became \"unavailable\" due to reaching the max_fails limit.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(angie_http_upstreams_peers_health_unavailable\n{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Peer Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(angie_http_upstreams_peers_data_sent{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}} - Data Received"
      },
      {
       "expr": "irate(angie_http_upstreams_peers_data_received{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}} - Data Sent"
      }
     ]
    },
    {
     "title": "Upstream Requests",
     "type": "timeseries",
     "description": "Number of attempts to use an upstream peer in \"HTTP\" (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_upstreams_peers_selected_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Requests In Progress",
     "type": "timeseries",
     "description": "The number of requests currently being processed by an upstream peer in \"HTTP\"",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "angie_http_upstreams_peers_selected_current{instance=\"$node\", job=\"$job\"}",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Keepalive Connections",
     "type": "timeseries",
     "description": "The number of currently cached keepalive connections for an HTTP upstream.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "angie_http_upstreams_keepalive{instance=\"$node\", job=\"$job\"}",
       "legendFormat": "{{upstream}}"
      }
     ]
    },
    {
     "title": "Upstream Peer Responses - 2xx/3xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (upstream,peer) (irate(angie_http_upstreams_peers_responses{instance=\"$node\", job=\"$job\", code=~\"^(1|2|3).*\"}[$__rate_interval]))",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Peer Responses - 4xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (upstream,peer) (irate(angie_http_upstreams_peers_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval]))",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Upstream Peer Responses - 5xx Codes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (upstream,peer) (irate(angie_http_upstreams_peers_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval]))",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Peer 4xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 4xx errors codes divided by all location zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_upstreams_peers_responses{instance=\"$node\", job=\"$job\", code=~\"^4.*\"}[$__rate_interval])) / increase(angie_http_upstreams_peers_selected_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    },
    {
     "title": "Peer 5xx Error Rate",
     "type": "timeseries",
     "description": "Amount of 4xx errors codes divided by all location zone requests",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum without (code) (increase(angie_http_upstreams_peers_responses{instance=\"$node\", job=\"$job\", code=~\"^5.*\"}[$__rate_interval])) / increase(angie_http_upstreams_peers_selected_total{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{upstream}}/{{peer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_size{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}}"
      }
     ]
    },
    {
     "title": "HTTP Cache Shard Size",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_shards_size{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{path}}"
      }
     ]
    },
    {
     "title": "HTTP Cache Processed Responses",
     "type": "timeseries",
     "description": "Number of responses processed in an HTTP cache zone with a specific cache status (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_responses{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Cache Processed Data",
     "type": "timeseries",
     "description": "Number of bytes processed in an HTTP cache zone with a specific cache status. (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_bytes{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Cache Written Responses",
     "type": "timeseries",
     "description": "Number of responses written to an HTTP cache zone with a specific cache status (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_responses_written{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Cache Written Data",
     "type": "timeseries",
     "description": "Number of bytes processed in an HTTP cache zone with a specific cache status. (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(angie_http_caches_bytes_written{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Limits",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP limit_conn Requests",
     "type": "timeseries",
     "description": "Number of requests processed by an HTTP limit_conn zone with a specific result (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_limit_conns{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP limit_reqs Requests",
     "type": "timeseries",
     "description": "number of requests processed by an HTTP limit_reqs zone with a specific result (per second)",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_http_limit_reqs{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Slabs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slab Usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "angie_slabs_pages_used{job=\"$job\", instance=\"$node\"} / (angie_slabs_pages_used{job=\"$job\", instance=\"$node\"} + angie_slabs_pages_free{job=\"$job\", instance=\"$node\"})",
       "legendFormat": "{{ zone }} - used pages"
      }
     ]
    },
    {
     "title": "Page Slot Usage",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "angie_slabs_pages_slots_used{job=\"$job\", instance=\"$node\"} / (angie_slabs_pages_slots_used{job=\"$job\", instance=\"$node\"} + angie_slabs_pages_slots_free{job=\"$job\", instance=\"$node\"})",
       "legendFormat": "{{ zone }} - size {{ size }}"
      }
     ]
    },
    {
     "title": "Page Allocation Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(angie_slabs_pages_slots_reqs{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{ zone }} - size {{ size }}"
      }
     ]
    },
    {
     "title": "Page Allocation Failures",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(angie_slabs_pages_slots_fails{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
       "legendFormat": "{{ zone }} - size {{ size }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resolvers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resolver Requests",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_resolvers_queries{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{type}}"
      }
     ]
    },
    {
     "title": "Resolver Responses",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(angie_resolvers_responses{instance=\"$node\", job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}