angie:
  cert_src: angie-repo.crt
  key_src: angie-repo.key
  cert_dest: /etc/ssl/angie/angie-repo.crt
  key_dest: /etc/ssl/angie/angie-repo.key
  conf_dest: /etc/angie/angie.conf
  base_auth: /etc/angie/.auth

sites:
  wordpress:
    site_agnie_config_path: /etc/angie/http.d/wordpress.conf
    url: "angie.redtomat.ru"
  tests_backend:
    site_agnie_config_path: /etc/angie/http.d/backend.conf
    url: "angie-backend.redtomat.ru"
  static:
    site_agnie_config_path: /etc/angie/http.d/static.conf
    url: "static.redtomat.ru"

acme:
  dirs:
    - rsa
    - ecdsa

local_backup:
  dir: "{{ playbook_dir }}/files/cert_backup"
  